spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/handgo?charset=utf8&useSSL=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    hibernate:
#      ddl-auto: update
    show-sql: true
server:
  port: 8888
#mybatis:
#  mapper-locations: classpath*:/mapper/**Mapper.xml
#  typeAliasesPackage: com.stackfing.entity