spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/handgo?charset=utf8&useSSL=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  thymeleaf:
    cache: false
    cache-period: 0
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  redis:
    host: localhost
server:
  port: 8888
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.stackfing.entity